["setup.cfg".mypy]
# https://mypy.readthedocs.io/en/stable/config_file.html
allow_redefinition = false
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "src"
plugins = "graphene_plugin"
python_version = 3.8

# Do not follow imports (except for ones found in typeshed)
follow_imports = "skip"

ignore_errors = false
implicit_reexport = false
local_partial_types = true

# Treat Optional per PEP 484
strict_equality = true
strict_optional = true

no_implicit_optional = true
show_column_numbers = true
show_error_codes = true

# Lint-style cleanliness for typing
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

# Ensure all execution paths are returning
warn_no_return = true

["setup.cfg".'mypy-uvicorn']
ignore_missing_imports = true

["setup.cfg".'mypy-grpc']
ignore_missing_imports = true

["setup.cfg".'mypy-grpc._channel']
ignore_missing_imports = true

["setup.cfg".'mypy-application.controllers.grpc.messages.*']
ignore_errors = true

["setup.cfg".'mypy-tests.*']
ignore_errors = true
